//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsPayment
    {
        public int Id { get; set; }
        public int Client { get; set; }
        public System.DateTime Month { get; set; }
        public string Due_Amount { get; set; }
        public string Paid_Amount { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
