//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
        public string Amount { get; set; }
        public System.DateTime FullPaymentuptodate { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
