//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchitectureEntitiesModel : DbContext
    {
        public ArchitectureEntitiesModel()
            : base("name=ArchitectureEntitiesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientsExpense> ClientsExpenses { get; set; }
        public virtual DbSet<ClientsPayment> ClientsPayments { get; set; }
        public virtual DbSet<ClientsView> ClientsViews { get; set; }
        public virtual DbSet<EshtiracksType> EshtiracksTypes { get; set; }
        public virtual DbSet<ExpenseListName> ExpenseListNames { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<tblMonth> tblMonths { get; set; }
    }
}
